question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "Klingons respect their disabled comrades, and those who are old, injured, and helpless.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Mythology",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Politics",
     "question": "George W. Bush lost the popular vote in the 2004 United States presidential election.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning"
                 "&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science: Mathematics",
     "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Sports",
     "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another"
                 " playable character directly.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Geography",
     "question": "You could walk from Norway to North Korea while only passing through Russia.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "The &quot;Gympie Stinger&quot; is the deadliest plant in the world.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
